/* soapUpdateProxy.cpp
   Generated by gSOAP 2.8.17r from /mnt/hgfs/APA/Projects/New Project/Update/Server/C++/Update/source.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapUpdateProxy.h"

UpdateProxy::UpdateProxy()
{	UpdateProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

UpdateProxy::UpdateProxy(const struct soap &_soap) : soap(_soap)
{ }

UpdateProxy::UpdateProxy(const char *url)
{	UpdateProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

UpdateProxy::UpdateProxy(soap_mode iomode)
{	UpdateProxy_init(iomode, iomode);
}

UpdateProxy::UpdateProxy(const char *url, soap_mode iomode)
{	UpdateProxy_init(iomode, iomode);
	soap_endpoint = url;
}

UpdateProxy::UpdateProxy(soap_mode imode, soap_mode omode)
{	UpdateProxy_init(imode, omode);
}

UpdateProxy::~UpdateProxy()
{ }

void UpdateProxy::UpdateProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://tempuri.org/ns1.xsd", NULL, NULL},
	{"ns", "urn:Update", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
}

void UpdateProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void UpdateProxy::reset()
{	destroy();
	soap_done(this);
	soap_initialize(this);
	UpdateProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void UpdateProxy::soap_noheader()
{	this->header = NULL;
}

const SOAP_ENV__Header *UpdateProxy::soap_header()
{	return this->header;
}

const SOAP_ENV__Fault *UpdateProxy::soap_fault()
{	return this->fault;
}

const char *UpdateProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *UpdateProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int UpdateProxy::soap_close_socket()
{	return soap_closesock(this);
}

int UpdateProxy::soap_force_close_socket()
{	return soap_force_closesock(this);
}

void UpdateProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void UpdateProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *UpdateProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int UpdateProxy::RequestForUpdate(const char *endpoint, const char *soap_action, ns1__SessionInfo &response)
{	struct soap *soap = this;
	struct ns__RequestForUpdate soap_tmp_ns__RequestForUpdate;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://www.yourdomain.com/Update.cgi";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns__RequestForUpdate(soap, &soap_tmp_ns__RequestForUpdate);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__RequestForUpdate(soap, &soap_tmp_ns__RequestForUpdate, "ns:RequestForUpdate", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__RequestForUpdate(soap, &soap_tmp_ns__RequestForUpdate, "ns:RequestForUpdate", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&response)
		return soap_closesock(soap);
	response.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	response.soap_get(soap, "ns1:SessionInfo", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int UpdateProxy::MakeSecureConnection(const char *endpoint, const char *soap_action, ns1__UpdateArguments *UpdateInfo, ns1__UpdateFilesList &response)
{	struct soap *soap = this;
	struct ns__MakeSecureConnection soap_tmp_ns__MakeSecureConnection;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://www.yourdomain.com/Update.cgi";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_ns__MakeSecureConnection.UpdateInfo = UpdateInfo;
	soap_serializeheader(soap);
	soap_serialize_ns__MakeSecureConnection(soap, &soap_tmp_ns__MakeSecureConnection);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__MakeSecureConnection(soap, &soap_tmp_ns__MakeSecureConnection, "ns:MakeSecureConnection", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__MakeSecureConnection(soap, &soap_tmp_ns__MakeSecureConnection, "ns:MakeSecureConnection", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&response)
		return soap_closesock(soap);
	response.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	response.soap_get(soap, "ns1:UpdateFilesList", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int UpdateProxy::DoUpdate(const char *endpoint, const char *soap_action, ns1__UpdateArguments *UpdateInfo, ns1__UpdateResponse &response)
{	struct soap *soap = this;
	struct ns__DoUpdate soap_tmp_ns__DoUpdate;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://www.yourdomain.com/Update.cgi";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_ns__DoUpdate.UpdateInfo = UpdateInfo;
	soap_serializeheader(soap);
	soap_serialize_ns__DoUpdate(soap, &soap_tmp_ns__DoUpdate);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__DoUpdate(soap, &soap_tmp_ns__DoUpdate, "ns:DoUpdate", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__DoUpdate(soap, &soap_tmp_ns__DoUpdate, "ns:DoUpdate", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&response)
		return soap_closesock(soap);
	response.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	response.soap_get(soap, "ns1:UpdateResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int UpdateProxy::EndUpdate(const char *endpoint, const char *soap_action, ns1__UpdateArguments *UpdateInfo, ns1__ErrorInfo &response)
{	struct soap *soap = this;
	struct ns__EndUpdate soap_tmp_ns__EndUpdate;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://www.yourdomain.com/Update.cgi";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_ns__EndUpdate.UpdateInfo = UpdateInfo;
	soap_serializeheader(soap);
	soap_serialize_ns__EndUpdate(soap, &soap_tmp_ns__EndUpdate);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__EndUpdate(soap, &soap_tmp_ns__EndUpdate, "ns:EndUpdate", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__EndUpdate(soap, &soap_tmp_ns__EndUpdate, "ns:EndUpdate", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&response)
		return soap_closesock(soap);
	response.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	response.soap_get(soap, "ns1:ErrorInfo", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
