/* soapUpdateProxy.h
   Generated by gSOAP 2.8.17r from /mnt/hgfs/APA/Projects/New Project/Update/Server/C++/Update/source.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapUpdateProxy_H
#define soapUpdateProxy_H
#include "soapH.h"

class SOAP_CMAC UpdateProxy : public soap
{ public:
	/// Endpoint URL of service 'UpdateProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	UpdateProxy();
	/// Construct from another engine state
	UpdateProxy(const struct soap&);
	/// Constructor with endpoint URL
	UpdateProxy(const char *url);
	/// Constructor with engine input+output mode control
	UpdateProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	UpdateProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	UpdateProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~UpdateProxy();
	/// Initializer used by constructors
	virtual	void UpdateProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'RequestForUpdate' (returns error code or SOAP_OK)
	virtual	int RequestForUpdate(ns1__SessionInfo &response) { return this->RequestForUpdate(NULL, NULL, response); }
	virtual	int RequestForUpdate(const char *endpoint, const char *soap_action, ns1__SessionInfo &response);

	/// Web service operation 'MakeSecureConnection' (returns error code or SOAP_OK)
	virtual	int MakeSecureConnection(ns1__UpdateArguments *UpdateInfo, ns1__UpdateFilesList &response) { return this->MakeSecureConnection(NULL, NULL, UpdateInfo, response); }
	virtual	int MakeSecureConnection(const char *endpoint, const char *soap_action, ns1__UpdateArguments *UpdateInfo, ns1__UpdateFilesList &response);

	/// Web service operation 'DoUpdate' (returns error code or SOAP_OK)
	virtual	int DoUpdate(ns1__UpdateArguments *UpdateInfo, ns1__UpdateResponse &response) { return this->DoUpdate(NULL, NULL, UpdateInfo, response); }
	virtual	int DoUpdate(const char *endpoint, const char *soap_action, ns1__UpdateArguments *UpdateInfo, ns1__UpdateResponse &response);

	/// Web service operation 'EndUpdate' (returns error code or SOAP_OK)
	virtual	int EndUpdate(ns1__UpdateArguments *UpdateInfo, ns1__ErrorInfo &response) { return this->EndUpdate(NULL, NULL, UpdateInfo, response); }
	virtual	int EndUpdate(const char *endpoint, const char *soap_action, ns1__UpdateArguments *UpdateInfo, ns1__ErrorInfo &response);
};
#endif
